# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingapp', '0002_remove_bugtrack_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtrack',
            name='upload_image',
            field=models.ImageField(default='null', upload_to='butrackimg/'),
        ),
    ]
