# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingapp', '0003_bugtrack_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtrack',
            name='final_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bugtrack',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bugtrack',
            name='reference',
            field=models.CharField(default='Not Available', max_length=40),
        ),
        migrations.AlterField(
            model_name='bugtrack',
            name='current_status',
            field=models.CharField(choices=[('N', 'NotCompleted'), ('O', 'Onprocess'), ('C', 'Completed')], default='N', max_length=2),
        ),
    ]
